// Code generated by cross-referencing CATStructs.xml against each command's
// actual handler body in CATCommands.cs (commit 4969b62f) — not hand-written,
// not inferred from the struct alone. See PROTOCOLS.md for the full
// methodology and for the ~100 ZZ commands deliberately left out of this
// table (composite/enum/multi-field encodings that don't fit the generic
// bool/unsigned/signed/action shapes below, plus mixer/VAC/front-panel
// hardware commands out of scope for a remote CLI).
//
// ZZTX (MOX button) and ZZTU (TUNE) are deliberately absent from this
// registry despite fitting the plain bool shape: both genuinely key the
// transmitter (console.CATPTT / console.TUN) and must never be reachable
// through a generic, ungated passthrough — see SetTuneCAT and the existing
// PTT command for their safety-gated equivalents.
package cat

// ZZKind is the wire-encoding shape of a ZZxx extended CAT field.
type ZZKind int

const (
	ZZBool     ZZKind = iota // "0"/"1"
	ZZUnsigned               // fixed-width zero-padded decimal, no sign
	ZZSigned                 // 1 sign char + fixed-width zero-padded |value|
	ZZAction                 // no parameters — a bare "<CODE>;" action/query
)

// String names a ZZKind for display (e.g. 'cat zz list').
func (k ZZKind) String() string {
	switch k {
	case ZZBool:
		return "bool"
	case ZZUnsigned:
		return "unsigned"
	case ZZSigned:
		return "signed"
	case ZZAction:
		return "action"
	default:
		return "?"
	}
}

// ZZField describes one ZZxx command's wire shape, as confirmed against its
// handler body in CATCommands.cs.
type ZZField struct {
	Code     string
	Desc     string
	Kind     ZZKind
	Width    int // total wire chars for the value (sign included, for ZZSigned)
	HasRange bool
	Min, Max int
}

// zzFields is every ZZxx command this package can send generically via
// SetZZ/GetZZ/SendZZ — see LookupZZField, ListZZFields, and
// cmd/thetisctl's "cat zz" command.
var zzFields = []ZZField{
	{Code: "ZZAA", Desc: "APF gain", Kind: ZZSigned, Width: 4, HasRange: true, Min: 0, Max: 100},
	{Code: "ZZAB", Desc: "APF bandwidth", Kind: ZZSigned, Width: 4, HasRange: true, Min: 10, Max: 150},
	{Code: "ZZAC", Desc: "Sets or reads the step size", Kind: ZZUnsigned, Width: 2, HasRange: false, Min: 0, Max: 0},
	{Code: "ZZAG", Desc: "extended AF Gain", Kind: ZZUnsigned, Width: 3, HasRange: true, Min: 0, Max: 100},
	{Code: "ZZAP", Desc: "Audio peak filter on off", Kind: ZZBool, Width: 0, HasRange: false, Min: 0, Max: 0},
	{Code: "ZZAR", Desc: "AGCRF", Kind: ZZSigned, Width: 4, HasRange: true, Min: -20, Max: 120},
	{Code: "ZZAS", Desc: "RX2 AGCT", Kind: ZZSigned, Width: 4, HasRange: true, Min: -20, Max: 120},
	{Code: "ZZAT", Desc: "APF tune", Kind: ZZSigned, Width: 4, HasRange: true, Min: -250, Max: 250},
	{Code: "ZZBA", Desc: "RX2 down one band", Kind: ZZAction, Width: 0, HasRange: false, Min: 0, Max: 0},
	{Code: "ZZBB", Desc: "RX2 up one band", Kind: ZZAction, Width: 0, HasRange: false, Min: 0, Max: 0},
	{Code: "ZZBD", Desc: "Band Down", Kind: ZZAction, Width: 0, HasRange: false, Min: 0, Max: 0},
	{Code: "ZZBG", Desc: "extended Band Group", Kind: ZZBool, Width: 0, HasRange: false, Min: 0, Max: 0},
	{Code: "ZZBI", Desc: "extended BIN status", Kind: ZZBool, Width: 0, HasRange: false, Min: 0, Max: 0},
	{Code: "ZZBR", Desc: "BCI Reject", Kind: ZZBool, Width: 0, HasRange: false, Min: 0, Max: 0},
	{Code: "ZZBU", Desc: "Band Up", Kind: ZZAction, Width: 0, HasRange: false, Min: 0, Max: 0},
	{Code: "ZZBY", Desc: "Closes the console", Kind: ZZAction, Width: 0, HasRange: false, Min: 0, Max: 0},
	{Code: "ZZCB", Desc: "Enable Break In", Kind: ZZBool, Width: 0, HasRange: false, Min: 0, Max: 0},
	{Code: "ZZCD", Desc: "CW Break In Delay", Kind: ZZUnsigned, Width: 4, HasRange: true, Min: 150, Max: 5000},
	{Code: "ZZCF", Desc: "Show CW Freq", Kind: ZZBool, Width: 0, HasRange: false, Min: 0, Max: 0},
	{Code: "ZZCI", Desc: "CW Iambic Enable", Kind: ZZBool, Width: 0, HasRange: false, Min: 0, Max: 0},
	{Code: "ZZCL", Desc: "extended CW Pitch", Kind: ZZUnsigned, Width: 4, HasRange: false, Min: 0, Max: 0},
	{Code: "ZZCM", Desc: "CW Monitor", Kind: ZZBool, Width: 0, HasRange: false, Min: 0, Max: 0},
	{Code: "ZZCN", Desc: "CTUN Enable", Kind: ZZBool, Width: 0, HasRange: false, Min: 0, Max: 0},
	{Code: "ZZCO", Desc: "RX2 CTUN Enable", Kind: ZZBool, Width: 0, HasRange: false, Min: 0, Max: 0},
	{Code: "ZZCP", Desc: "extended Compander status", Kind: ZZBool, Width: 0, HasRange: false, Min: 0, Max: 0},
	{Code: "ZZCS", Desc: "extended CW Speed", Kind: ZZUnsigned, Width: 2, HasRange: false, Min: 0, Max: 0},
	{Code: "ZZCT", Desc: "CPDR Threshold", Kind: ZZUnsigned, Width: 2, HasRange: false, Min: 0, Max: 0},
	{Code: "ZZCU", Desc: "extended CPU Usage", Kind: ZZAction, Width: 0, HasRange: false, Min: 0, Max: 0},
	{Code: "ZZDA", Desc: "extended Display Average", Kind: ZZBool, Width: 0, HasRange: false, Min: 0, Max: 0},
	{Code: "ZZDB", Desc: "Diversity RX reference", Kind: ZZBool, Width: 0, HasRange: false, Min: 0, Max: 0},
	{Code: "ZZDC", Desc: "Diversity RX2 Gain", Kind: ZZUnsigned, Width: 4, HasRange: true, Min: 0, Max: 5000},
	{Code: "ZZDD", Desc: "Diversity Phase", Kind: ZZSigned, Width: 6, HasRange: true, Min: -18000, Max: 18000},
	{Code: "ZZDE", Desc: "Diversity Form Enable", Kind: ZZBool, Width: 0, HasRange: false, Min: 0, Max: 0},
	{Code: "ZZDF", Desc: "CAT Diversity Form", Kind: ZZBool, Width: 0, HasRange: false, Min: 0, Max: 0},
	{Code: "ZZDG", Desc: "Diversity RX1 Gain", Kind: ZZUnsigned, Width: 4, HasRange: true, Min: 0, Max: 1000},
	{Code: "ZZDH", Desc: "Diversity RX Source", Kind: ZZBool, Width: 0, HasRange: false, Min: 0, Max: 0},
	{Code: "ZZDN", Desc: "Waterfall Low Level", Kind: ZZSigned, Width: 4, HasRange: false, Min: 0, Max: 0},
	{Code: "ZZDO", Desc: "Waterfall High Level", Kind: ZZSigned, Width: 4, HasRange: false, Min: 0, Max: 0},
	{Code: "ZZDP", Desc: "Sprectrum Grid Max", Kind: ZZSigned, Width: 4, HasRange: false, Min: 0, Max: 0},
	{Code: "ZZDQ", Desc: "Spectrum Grid Min", Kind: ZZSigned, Width: 4, HasRange: false, Min: 0, Max: 0},
	{Code: "ZZDR", Desc: "Spectrum Grid Step", Kind: ZZUnsigned, Width: 2, HasRange: false, Min: 0, Max: 0},
	{Code: "ZZDT", Desc: "RADE RX decoder-input level/clip status", Kind: ZZAction, Width: 0, HasRange: false, Min: 0, Max: 0},
	{Code: "ZZDU", Desc: "DDUTil Status", Kind: ZZAction, Width: 0, HasRange: false, Min: 0, Max: 0},
	{Code: "ZZEM", Desc: "Verbose CAT Errors", Kind: ZZBool, Width: 0, HasRange: false, Min: 0, Max: 0},
	{Code: "ZZER", Desc: "RXEQ button status", Kind: ZZBool, Width: 0, HasRange: false, Min: 0, Max: 0},
	{Code: "ZZET", Desc: "TXEQ button status", Kind: ZZBool, Width: 0, HasRange: false, Min: 0, Max: 0},
	{Code: "ZZFH", Desc: "DSP Filter High", Kind: ZZSigned, Width: 5, HasRange: true, Min: -10000, Max: 10000},
	{Code: "ZZFI", Desc: "extended current filter name", Kind: ZZUnsigned, Width: 2, HasRange: false, Min: 0, Max: 0},
	{Code: "ZZFJ", Desc: "RX2 DSP Filter", Kind: ZZUnsigned, Width: 2, HasRange: false, Min: 0, Max: 0},
	{Code: "ZZFL", Desc: "DSP Filter Low", Kind: ZZSigned, Width: 5, HasRange: true, Min: -10000, Max: 10000},
	{Code: "ZZFM", Desc: "Flex Model Number", Kind: ZZAction, Width: 0, HasRange: false, Min: 0, Max: 0},
	{Code: "ZZFR", Desc: "RX2 DSP Filter High", Kind: ZZSigned, Width: 5, HasRange: true, Min: -10000, Max: 10000},
	{Code: "ZZFS", Desc: "RX2 DSP Filter Low", Kind: ZZSigned, Width: 5, HasRange: true, Min: -10000, Max: 10000},
	{Code: "ZZFV", Desc: "FlexWire single read", Kind: ZZAction, Width: 0, HasRange: false, Min: 0, Max: 0},
	{Code: "ZZFW", Desc: "FlexWire double read", Kind: ZZAction, Width: 0, HasRange: false, Min: 0, Max: 0},
	{Code: "ZZGE", Desc: "Noise Gate Enable", Kind: ZZBool, Width: 0, HasRange: false, Min: 0, Max: 0},
	{Code: "ZZGL", Desc: "Noise Gate Level", Kind: ZZSigned, Width: 4, HasRange: true, Min: -160, Max: 0},
	{Code: "ZZID", Desc: "extended SetRigType", Kind: ZZAction, Width: 0, HasRange: false, Min: 0, Max: 0},
	{Code: "ZZIF", Desc: "extended Xcvr Status", Kind: ZZAction, Width: 0, HasRange: false, Min: 0, Max: 0},
	{Code: "ZZIO", Desc: "Installed options", Kind: ZZAction, Width: 0, HasRange: false, Min: 0, Max: 0},
	{Code: "ZZIS", Desc: "extended IF shift", Kind: ZZUnsigned, Width: 5, HasRange: false, Min: 0, Max: 0},
	{Code: "ZZIT", Desc: "extended Filter Shift", Kind: ZZSigned, Width: 5, HasRange: false, Min: 0, Max: 0},
	{Code: "ZZIU", Desc: "extended Filter Shift Reset", Kind: ZZAction, Width: 0, HasRange: false, Min: 0, Max: 0},
	{Code: "ZZJS", Desc: "Stop Wav Recording or Playback", Kind: ZZAction, Width: 0, HasRange: false, Min: 0, Max: 0},
	{Code: "ZZKO", Desc: "CWX Form Control", Kind: ZZBool, Width: 0, HasRange: false, Min: 0, Max: 0},
	{Code: "ZZKS", Desc: "CWX CW Speed", Kind: ZZUnsigned, Width: 3, HasRange: true, Min: 1, Max: 99},
	{Code: "ZZLA", Desc: "RX0 Gain", Kind: ZZUnsigned, Width: 3, HasRange: true, Min: 0, Max: 100},
	{Code: "ZZLB", Desc: "RX0 Stereo Bal", Kind: ZZUnsigned, Width: 3, HasRange: true, Min: 0, Max: 100},
	{Code: "ZZLC", Desc: "RX1 Gain", Kind: ZZUnsigned, Width: 3, HasRange: true, Min: 0, Max: 100},
	{Code: "ZZLD", Desc: "RX1 Stereo Bal", Kind: ZZUnsigned, Width: 3, HasRange: true, Min: 0, Max: 100},
	{Code: "ZZLE", Desc: "RX2 audio level", Kind: ZZUnsigned, Width: 3, HasRange: true, Min: 0, Max: 100},
	{Code: "ZZLF", Desc: "RX2 Stereo Balance", Kind: ZZUnsigned, Width: 3, HasRange: true, Min: 0, Max: 100},
	{Code: "ZZLI", Desc: "PS-A Enable Button", Kind: ZZBool, Width: 0, HasRange: false, Min: 0, Max: 0},
	{Code: "ZZMA", Desc: "extended MUT function", Kind: ZZBool, Width: 0, HasRange: false, Min: 0, Max: 0},
	{Code: "ZZMB", Desc: "RX2 Mute", Kind: ZZBool, Width: 0, HasRange: false, Min: 0, Max: 0},
	{Code: "ZZMG", Desc: "extended TX Preamp Gain", Kind: ZZSigned, Width: 3, HasRange: true, Min: -50, Max: 70},
	{Code: "ZZML", Desc: "Mode List", Kind: ZZAction, Width: 0, HasRange: false, Min: 0, Max: 0},
	{Code: "ZZMN", Desc: "Filter Presets", Kind: ZZAction, Width: 0, HasRange: false, Min: 0, Max: 0},
	{Code: "ZZMO", Desc: "Monitor button", Kind: ZZBool, Width: 0, HasRange: false, Min: 0, Max: 0},
	{Code: "ZZMS", Desc: "MultiRX Swap checkbox status", Kind: ZZBool, Width: 0, HasRange: false, Min: 0, Max: 0},
	{Code: "ZZMU", Desc: "MultiRX button status", Kind: ZZBool, Width: 0, HasRange: false, Min: 0, Max: 0},
	{Code: "ZZMV", Desc: "Get Memory Channel Count", Kind: ZZAction, Width: 0, HasRange: false, Min: 0, Max: 0},
	{Code: "ZZMW", Desc: "Get Memory Channel Name", Kind: ZZAction, Width: 0, HasRange: false, Min: 0, Max: 0},
	{Code: "ZZMY", Desc: "Save Memory Channel", Kind: ZZAction, Width: 0, HasRange: false, Min: 0, Max: 0},
	{Code: "ZZNA", Desc: "Noise Blanker 1 button status", Kind: ZZBool, Width: 0, HasRange: false, Min: 0, Max: 0},
	{Code: "ZZNB", Desc: "extended nb2 status", Kind: ZZBool, Width: 0, HasRange: false, Min: 0, Max: 0},
	{Code: "ZZNC", Desc: "RX2 NB Button", Kind: ZZBool, Width: 0, HasRange: false, Min: 0, Max: 0},
	{Code: "ZZND", Desc: "RX2 NB2 Button", Kind: ZZBool, Width: 0, HasRange: false, Min: 0, Max: 0},
	{Code: "ZZNE", Desc: "Improved rx1 nr status", Kind: ZZBool, Width: 0, HasRange: false, Min: 0, Max: 0},
	{Code: "ZZNF", Desc: "Improved rx2 nr status", Kind: ZZBool, Width: 0, HasRange: false, Min: 0, Max: 0},
	{Code: "ZZNG", Desc: "Rx1 NR4 reduction amount", Kind: ZZUnsigned, Width: 3, HasRange: false, Min: 0, Max: 0},
	{Code: "ZZNH", Desc: "Rx2 NR4 reduction amount", Kind: ZZUnsigned, Width: 3, HasRange: false, Min: 0, Max: 0},
	{Code: "ZZNL", Desc: "extended nb1 threshold", Kind: ZZUnsigned, Width: 3, HasRange: false, Min: 0, Max: 0},
	{Code: "ZZNM", Desc: "extended nb2 threshold", Kind: ZZUnsigned, Width: 4, HasRange: false, Min: 0, Max: 0},
	{Code: "ZZNN", Desc: "RX1 SNB Button", Kind: ZZBool, Width: 0, HasRange: false, Min: 0, Max: 0},
	{Code: "ZZNO", Desc: "RX2 SNB Button", Kind: ZZBool, Width: 0, HasRange: false, Min: 0, Max: 0},
	{Code: "ZZNR", Desc: "extended rx1 nr status", Kind: ZZBool, Width: 0, HasRange: false, Min: 0, Max: 0},
	{Code: "ZZNS", Desc: "extended rx1 nr2 status", Kind: ZZBool, Width: 0, HasRange: false, Min: 0, Max: 0},
	{Code: "ZZNT", Desc: "ANF status", Kind: ZZBool, Width: 0, HasRange: false, Min: 0, Max: 0},
	{Code: "ZZNU", Desc: "RX2 ANF status", Kind: ZZBool, Width: 0, HasRange: false, Min: 0, Max: 0},
	{Code: "ZZNV", Desc: "extended rx2 nr status", Kind: ZZBool, Width: 0, HasRange: false, Min: 0, Max: 0},
	{Code: "ZZNW", Desc: "extended rx2 nr2 status", Kind: ZZBool, Width: 0, HasRange: false, Min: 0, Max: 0},
	{Code: "ZZOL", Desc: "DigL Click Tune Offset", Kind: ZZUnsigned, Width: 4, HasRange: true, Min: 0, Max: 10000},
	{Code: "ZZOU", Desc: "DigU Click Tune Offset", Kind: ZZUnsigned, Width: 4, HasRange: true, Min: 0, Max: 10000},
	{Code: "ZZPC", Desc: "Drive Level", Kind: ZZUnsigned, Width: 3, HasRange: false, Min: 0, Max: 0},
	{Code: "ZZPD", Desc: "Center Display Pan", Kind: ZZAction, Width: 0, HasRange: false, Min: 0, Max: 0},
	{Code: "ZZPE", Desc: "Display Pan Position", Kind: ZZUnsigned, Width: 4, HasRange: true, Min: 0, Max: 1000},
	{Code: "ZZPY", Desc: "Disply Zoom", Kind: ZZUnsigned, Width: 3, HasRange: true, Min: 10, Max: 240},
	{Code: "ZZQK", Desc: "Enable QSK Break In", Kind: ZZBool, Width: 0, HasRange: false, Min: 0, Max: 0},
	{Code: "ZZQM", Desc: "extended Quick Memory Value", Kind: ZZAction, Width: 0, HasRange: false, Min: 0, Max: 0},
	{Code: "ZZQR", Desc: "Quick Memory Restore", Kind: ZZAction, Width: 0, HasRange: false, Min: 0, Max: 0},
	{Code: "ZZQS", Desc: "Quick Memory Save", Kind: ZZAction, Width: 0, HasRange: false, Min: 0, Max: 0},
	{Code: "ZZRA", Desc: "RTTY Offset Enable A", Kind: ZZBool, Width: 0, HasRange: false, Min: 0, Max: 0},
	{Code: "ZZRB", Desc: "RTTY Offset Enable B", Kind: ZZBool, Width: 0, HasRange: false, Min: 0, Max: 0},
	{Code: "ZZRC", Desc: "RIT freq clear", Kind: ZZAction, Width: 0, HasRange: false, Min: 0, Max: 0},
	{Code: "ZZRF", Desc: "extended RIT Value", Kind: ZZSigned, Width: 5, HasRange: true, Min: -99999, Max: 99999},
	{Code: "ZZRH", Desc: "RTTY DIGH offset freq", Kind: ZZSigned, Width: 5, HasRange: true, Min: -3000, Max: 3000},
	{Code: "ZZRL", Desc: "RTTY DIGL offset freq", Kind: ZZSigned, Width: 5, HasRange: true, Min: -3000, Max: 3000},
	{Code: "ZZRM", Desc: "extended TX Meter Output", Kind: ZZAction, Width: 0, HasRange: false, Min: 0, Max: 0},
	{Code: "ZZRS", Desc: "RX2 Enable", Kind: ZZBool, Width: 0, HasRange: false, Min: 0, Max: 0},
	{Code: "ZZRV", Desc: "Primary Input Voltage", Kind: ZZAction, Width: 0, HasRange: false, Min: 0, Max: 0},
	{Code: "ZZRY", Desc: "RX2 Atten", Kind: ZZUnsigned, Width: 2, HasRange: true, Min: 0, Max: 31},
	{Code: "ZZSA", Desc: "Step Down", Kind: ZZAction, Width: 0, HasRange: false, Min: 0, Max: 0},
	{Code: "ZZSB", Desc: "Step Up", Kind: ZZAction, Width: 0, HasRange: false, Min: 0, Max: 0},
	{Code: "ZZSD", Desc: "Tune Step Down", Kind: ZZAction, Width: 0, HasRange: false, Min: 0, Max: 0},
	{Code: "ZZSG", Desc: "Step Down", Kind: ZZAction, Width: 0, HasRange: false, Min: 0, Max: 0},
	{Code: "ZZSH", Desc: "Step Up", Kind: ZZAction, Width: 0, HasRange: false, Min: 0, Max: 0},
	{Code: "ZZSM", Desc: "extended S Meter", Kind: ZZAction, Width: 0, HasRange: false, Min: 0, Max: 0},
	{Code: "ZZSN", Desc: "Radio serial number", Kind: ZZAction, Width: 0, HasRange: false, Min: 0, Max: 0},
	{Code: "ZZSO", Desc: "extended Squelch status", Kind: ZZBool, Width: 0, HasRange: false, Min: 0, Max: 0},
	{Code: "ZZSQ", Desc: "extended Squelch Control", Kind: ZZUnsigned, Width: 3, HasRange: true, Min: 0, Max: 100},
	{Code: "ZZSR", Desc: "Spur Reduction", Kind: ZZBool, Width: 0, HasRange: false, Min: 0, Max: 0},
	{Code: "ZZSS", Desc: "CWX Stop", Kind: ZZAction, Width: 0, HasRange: false, Min: 0, Max: 0},
	{Code: "ZZST", Desc: "extended step size", Kind: ZZAction, Width: 0, HasRange: false, Min: 0, Max: 0},
	{Code: "ZZSU", Desc: "Tune Step Up", Kind: ZZAction, Width: 0, HasRange: false, Min: 0, Max: 0},
	{Code: "ZZSV", Desc: "RX2 Squelch Button", Kind: ZZBool, Width: 0, HasRange: false, Min: 0, Max: 0},
	{Code: "ZZSW", Desc: "Swap VFO A/B TX Buttons", Kind: ZZBool, Width: 0, HasRange: false, Min: 0, Max: 0},
	{Code: "ZZSX", Desc: "RX2 Squelch Threshold", Kind: ZZUnsigned, Width: 3, HasRange: true, Min: 0, Max: 100},
	{Code: "ZZSY", Desc: "VFO Sync Button", Kind: ZZBool, Width: 0, HasRange: false, Min: 0, Max: 0},
	{Code: "ZZTA", Desc: "CTCSS Enable", Kind: ZZBool, Width: 0, HasRange: false, Min: 0, Max: 0},
	{Code: "ZZTF", Desc: "Show TX Filter", Kind: ZZBool, Width: 0, HasRange: false, Min: 0, Max: 0},
	{Code: "ZZTH", Desc: "extended TX Filter High", Kind: ZZUnsigned, Width: 5, HasRange: true, Min: 500, Max: 20000},
	{Code: "ZZTI", Desc: "Transmit Inhibit", Kind: ZZBool, Width: 0, HasRange: false, Min: 0, Max: 0},
	{Code: "ZZTL", Desc: "extended TX Filter Low", Kind: ZZUnsigned, Width: 4, HasRange: true, Min: 0, Max: 2000},
	{Code: "ZZTM", Desc: "TX AF Monitor Gain", Kind: ZZUnsigned, Width: 3, HasRange: true, Min: 0, Max: 100},
	{Code: "ZZTO", Desc: "Tune Power", Kind: ZZUnsigned, Width: 3, HasRange: true, Min: 0, Max: 100},
	{Code: "ZZTP", Desc: "TX ProfileCount", Kind: ZZUnsigned, Width: 2, HasRange: false, Min: 0, Max: 0},
	{Code: "ZZTS", Desc: "Read F5K Temp Sensor", Kind: ZZAction, Width: 0, HasRange: false, Min: 0, Max: 0},
	{Code: "ZZUA", Desc: "XVTR Band Names", Kind: ZZAction, Width: 0, HasRange: false, Min: 0, Max: 0},
	{Code: "ZZUP", Desc: "External PA button", Kind: ZZBool, Width: 0, HasRange: false, Min: 0, Max: 0},
	{Code: "ZZUS", Desc: "PS Single Cal activate ", Kind: ZZAction, Width: 0, HasRange: false, Min: 0, Max: 0},
	{Code: "ZZUT", Desc: "extended Two-tone test status", Kind: ZZBool, Width: 0, HasRange: false, Min: 0, Max: 0},
	{Code: "ZZUX", Desc: "extended VFOA Lock status", Kind: ZZBool, Width: 0, HasRange: false, Min: 0, Max: 0},
	{Code: "ZZUY", Desc: "extended VFOB Lock status", Kind: ZZBool, Width: 0, HasRange: false, Min: 0, Max: 0},
	{Code: "ZZVA", Desc: "VAC Enable", Kind: ZZBool, Width: 0, HasRange: false, Min: 0, Max: 0},
	{Code: "ZZVB", Desc: "VAC RX Gain", Kind: ZZSigned, Width: 3, HasRange: true, Min: -40, Max: 40},
	{Code: "ZZVC", Desc: "VAC TX Gain", Kind: ZZSigned, Width: 3, HasRange: true, Min: -40, Max: 40},
	{Code: "ZZVE", Desc: "VOX Enable", Kind: ZZBool, Width: 0, HasRange: false, Min: 0, Max: 0},
	{Code: "ZZVF", Desc: "VAC Stereo", Kind: ZZBool, Width: 0, HasRange: false, Min: 0, Max: 0},
	{Code: "ZZVG", Desc: "VOX Gain", Kind: ZZUnsigned, Width: 4, HasRange: true, Min: 0, Max: 1000},
	{Code: "ZZVH", Desc: "IQ2VAC", Kind: ZZBool, Width: 0, HasRange: false, Min: 0, Max: 0},
	{Code: "ZZVI", Desc: "VAC Input Cable", Kind: ZZUnsigned, Width: 2, HasRange: false, Min: 0, Max: 0},
	{Code: "ZZVJ", Desc: "VAC Use RX2", Kind: ZZBool, Width: 0, HasRange: false, Min: 0, Max: 0},
	{Code: "ZZVK", Desc: "VAC2Enable", Kind: ZZBool, Width: 0, HasRange: false, Min: 0, Max: 0},
	{Code: "ZZVL", Desc: "extended VFO Lock status", Kind: ZZBool, Width: 0, HasRange: false, Min: 0, Max: 0},
	{Code: "ZZVM", Desc: "VAC Driver", Kind: ZZUnsigned, Width: 2, HasRange: false, Min: 0, Max: 0},
	{Code: "ZZVN", Desc: "extended Get Version", Kind: ZZAction, Width: 0, HasRange: false, Min: 0, Max: 0},
	{Code: "ZZVO", Desc: "VAC Output Cable", Kind: ZZUnsigned, Width: 2, HasRange: false, Min: 0, Max: 0},
	{Code: "ZZVP", Desc: "VAC1Calibrate", Kind: ZZBool, Width: 0, HasRange: false, Min: 0, Max: 0},
	{Code: "ZZVQ", Desc: "VAC2Driver", Kind: ZZUnsigned, Width: 2, HasRange: false, Min: 0, Max: 0},
	{Code: "ZZVR", Desc: "VAC2InputCable", Kind: ZZUnsigned, Width: 2, HasRange: false, Min: 0, Max: 0},
	{Code: "ZZVT", Desc: "VAC2OutputCable", Kind: ZZUnsigned, Width: 2, HasRange: false, Min: 0, Max: 0},
	{Code: "ZZVV", Desc: "VAC2Stereo", Kind: ZZBool, Width: 0, HasRange: false, Min: 0, Max: 0},
	{Code: "ZZVW", Desc: "VAC2RXGain", Kind: ZZSigned, Width: 3, HasRange: true, Min: -40, Max: 40},
	{Code: "ZZVX", Desc: "VAC2TXGain", Kind: ZZSigned, Width: 3, HasRange: true, Min: -40, Max: 40},
	{Code: "ZZXA", Desc: "Audio Amp", Kind: ZZBool, Width: 0, HasRange: false, Min: 0, Max: 0},
	{Code: "ZZXC", Desc: "extended XIT Clear", Kind: ZZAction, Width: 0, HasRange: false, Min: 0, Max: 0},
	{Code: "ZZXF", Desc: "extended XIT Value", Kind: ZZSigned, Width: 5, HasRange: true, Min: -99999, Max: 99999},
	{Code: "ZZXH", Desc: "VOX Hang time", Kind: ZZUnsigned, Width: 4, HasRange: true, Min: 0, Max: 4000},
	{Code: "ZZXN", Desc: "RX1 Combined Status", Kind: ZZAction, Width: 0, HasRange: false, Min: 0, Max: 0},
	{Code: "ZZXO", Desc: "RX2 Combined Status", Kind: ZZAction, Width: 0, HasRange: false, Min: 0, Max: 0},
	{Code: "ZZXT", Desc: "X2TR", Kind: ZZBool, Width: 0, HasRange: false, Min: 0, Max: 0},
	{Code: "ZZXV", Desc: "VFO Combined Status", Kind: ZZAction, Width: 0, HasRange: false, Min: 0, Max: 0},
	{Code: "ZZYA", Desc: "VAC2DirectIQ", Kind: ZZBool, Width: 0, HasRange: false, Min: 0, Max: 0},
	{Code: "ZZYB", Desc: "VAC2Calibrate", Kind: ZZBool, Width: 0, HasRange: false, Min: 0, Max: 0},
	{Code: "ZZYC", Desc: "FM Mic Gain", Kind: ZZUnsigned, Width: 2, HasRange: true, Min: 0, Max: 70},
	{Code: "ZZYR", Desc: "RX1/RX2 radio button", Kind: ZZBool, Width: 0, HasRange: false, Min: 0, Max: 0},
	{Code: "ZZZB", Desc: "Zero Beat", Kind: ZZAction, Width: 0, HasRange: false, Min: 0, Max: 0},
	{Code: "ZZZM", Desc: "Get Hardware Model", Kind: ZZAction, Width: 0, HasRange: false, Min: 0, Max: 0},
	{Code: "ZZZN", Desc: "Enable Quick Split", Kind: ZZBool, Width: 0, HasRange: false, Min: 0, Max: 0},
	{Code: "ZZZO", Desc: "Enable Quick Split and VFO Split", Kind: ZZBool, Width: 0, HasRange: false, Min: 0, Max: 0},
	{Code: "ZZZQ", Desc: "RX1 Auto AGC compensation", Kind: ZZBool, Width: 0, HasRange: false, Min: 0, Max: 0},
	{Code: "ZZZR", Desc: "RX2 Auto AGC compensation", Kind: ZZBool, Width: 0, HasRange: false, Min: 0, Max: 0},
	{Code: "ZZZT", Desc: "Zoom To Band Recall/Store", Kind: ZZBool, Width: 0, HasRange: false, Min: 0, Max: 0},
	{Code: "ZZZV", Desc: "Get Software Version String", Kind: ZZAction, Width: 0, HasRange: false, Min: 0, Max: 0},
	{Code: "ZZZW", Desc: "Get SwapVFOWheels state", Kind: ZZBool, Width: 0, HasRange: false, Min: 0, Max: 0},
	{Code: "ZZZZ", Desc: "Close Serial Port", Kind: ZZAction, Width: 0, HasRange: false, Min: 0, Max: 0},
}
